# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../platform.h \
    ./DeckLinkDevice.h \
    ./GeneratedFiles/ui_CapturePreviewEx.h \
    ./CapturePreviewExWindow.h
SOURCES += ../../amdovx-modules-master/utils/loom_shell/loom_shell_util.cpp \
    ./CapturePreviewExWindow.cpp \
    ./DeckLinkAPI_i.c \
    ./DeckLinkDevice.cpp \
    ./GeneratedFiles/Debug/moc_CapturePreviewExWindow.cpp \
    ./GeneratedFiles/qrc_CapturePreviewEx.cpp \
    ./main.cpp \
    ./platform.cpp
FORMS += ./CapturePreviewEx.ui
RESOURCES += CapturePreviewEx.qrc
