/* -LICENSE-START-
** Copyright (c) 2013 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
**
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

// CapturePreviewDlg.cpp : implementation file
//

#include "stdafx.h"
#include "CapturePreview.h"
#include "CapturePreviewDlg.h"
#include "DeckLinkDevice.h"
#include<iostream>
#include<string>
#include<strstream>
#ifdef _DEBUG
#define new DEBUG_NEW
#endif


using namespace std;

CCapturePreviewDlg::CCapturePreviewDlg(CWnd* pParent)
	: CDialog(CCapturePreviewDlg::IDD, pParent), m_deckLinkDiscovery(NULL),
	m_selectedDevice(NULL), device_count(0)
{
	m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);
}

void CCapturePreviewDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	DDX_Control(pDX, IDC_INPUT_DEVICE_COMBO, m_deviceListCombo);
	DDX_Control(pDX, IDC_AUTODETECT_FORMAT_CHECK, m_applyDetectedInputModeCheckbox);
	DDX_Control(pDX, IDC_INPUT_MODE_COMBO, m_modeListCombo);
	DDX_Control(pDX, IDC_START_STOP_BUTTON, m_startStopButton);
	DDX_Control(pDX, IDC_START_STOP_BUTTON2, m_startStopButton2);
	DDX_Control(pDX, IDC_START_STOP_BUTTON3, m_startStopButton3);
	DDX_Control(pDX, IDC_START_STOP_BUTTON4, m_startStopButton4);

	DDX_Control(pDX, IDC_INVALID_INPUT_STATIC, m_invalidInputLabel);

	DDX_Control(pDX, IDC_VITC_TC_F1_STATIC, m_vitcTcF1);
	DDX_Control(pDX, IDC_VITC_UB_F1_STATIC, m_vitcUbF1);
	DDX_Control(pDX, IDC_VITC_TC_F2_STATIC, m_vitcTcF2);
	DDX_Control(pDX, IDC_VITC_UB_F2__STATIC, m_vitcUbF2);

	DDX_Control(pDX, IDC_RP188_VITC1_TC_STATIC, m_rp188Vitc1Tc);
	DDX_Control(pDX, IDC_RP188_VITC1_UB_STATIC, m_rp188Vitc1Ub);
	DDX_Control(pDX, IDC_RP188_VITC2_TC_STATIC, m_rp188Vitc2Tc);
	DDX_Control(pDX, IDC_RP188_VITC2_TC__STATIC, m_rp188Vitc2Ub);
	DDX_Control(pDX, IDC_RP188_LTC_TC_STATIC, m_rp188LtcTc);
	DDX_Control(pDX, IDC_RP188_LTC_UB_STATIC, m_rp188LtcUb);

	DDX_Control(pDX, IDC_PREVIEW_BOX, m_previewBox);
	DDX_Control(pDX, IDC_PREVIEW_BOX2, m_previewBox2);
	DDX_Control(pDX, IDC_PREVIEW_BOX3, m_previewBox3);
	DDX_Control(pDX, IDC_PREVIEW_BOX4, m_previewBox4);
}

BEGIN_MESSAGE_MAP(CCapturePreviewDlg, CDialog)
	ON_WM_PAINT()
	ON_WM_QUERYDRAGICON()
	ON_WM_CLOSE()

	// UI element messages
	ON_BN_CLICKED(IDC_START_STOP_BUTTON, &CCapturePreviewDlg::OnStartStopBnClicked)
	ON_CBN_SELCHANGE(IDC_INPUT_DEVICE_COMBO, &CCapturePreviewDlg::OnNewDeviceSelected)

	// Custom messages
	ON_MESSAGE(WM_REFRESH_INPUT_STREAM_DATA_MESSAGE, &CCapturePreviewDlg::OnRefreshInputStreamData)
	ON_MESSAGE(WM_SELECT_VIDEO_MODE_MESSAGE, &CCapturePreviewDlg::OnSelectVideoMode)
	ON_MESSAGE(WM_ADD_DEVICE_MESSAGE, &CCapturePreviewDlg::OnAddDevice)
	ON_MESSAGE(WM_REMOVE_DEVICE_MESSAGE, &CCapturePreviewDlg::OnRemoveDevice)
	ON_MESSAGE(WM_ERROR_RESTARTING_CAPTURE_MESSAGE, &CCapturePreviewDlg::OnErrorRestartingCapture)
	ON_BN_CLICKED(IDC_START_STOP_BUTTON2, &CCapturePreviewDlg::OnBnClickedStartStopButton2)
	ON_BN_CLICKED(IDC_START_STOP_BUTTON3, &CCapturePreviewDlg::OnBnClickedStartStopButton3)
	ON_BN_CLICKED(IDC_START_STOP_BUTTON4, &CCapturePreviewDlg::OnBnClickedStartStopButton4)
END_MESSAGE_MAP()

void CCapturePreviewDlg::OnStartStopBnClicked()
{
	if (m_selectedDevice == NULL)
		return;

	if (m_selectedDevice->IsCapturing())
		StopCapture();
	else
		StartCapture();
}
#if 1
void CCapturePreviewDlg::OnNewDeviceSelected()
{
	int		selectedDeviceIndex;

	selectedDeviceIndex = m_deviceListCombo.GetCurSel();
	if (selectedDeviceIndex < 0)
		return;

	m_selectedDevice = (DeckLinkDevice*)m_deviceListCombo.GetItemDataPtr(selectedDeviceIndex);

	// Update the video mode popup menu
	RefreshVideoModeList();

	// Enable the interface
	EnableInterface(true);

	if (m_selectedDevice->SupportsFormatDetection())
		m_applyDetectedInputModeCheckbox.SetCheck(BST_CHECKED);
}
#else
void CCapturePreviewDlg::OnNewDeviceSelected()
{
	int		selectedDeviceIndex;

	selectedDeviceIndex = m_deviceListCombo.GetCurSel();
	if (selectedDeviceIndex < 0)
		return;

	m_selectedDevice = (DeckLinkDevice*)m_deviceListCombo.GetItemDataPtr(selectedDeviceIndex);

	// Update the video mode popup menu
	RefreshVideoModeList();

	// Enable the interface
	EnableInterface(true);

	if (m_selectedDevice->SupportsFormatDetection())
		m_applyDetectedInputModeCheckbox.SetCheck(BST_CHECKED);
}
#endif
void CCapturePreviewDlg::OnClose()
{
	RemoveDevice(m_pDeckLink);
	// Stop the capture
	//StopCapture();

	// Release all DeckLinkDevice instances
	while (m_deviceListCombo.GetCount() > 0)
	{
		DeckLinkDevice* device = (DeckLinkDevice*)m_deviceListCombo.GetItemDataPtr(0);
		device->Release();
		m_deviceListCombo.DeleteString(0);
	}

	if (m_previewWindow != NULL)
	{
		delete m_previewWindow;
		m_previewWindow = NULL;
	}

	// Release DeckLink discovery instance
	if (m_deckLinkDiscovery != NULL)
	{
		m_deckLinkDiscovery->Disable();
		m_deckLinkDiscovery->Release();
		m_deckLinkDiscovery = NULL;
	}

	CDialog::OnClose();
}


void CCapturePreviewDlg::ShowErrorMessage(TCHAR* msg, TCHAR* title)
{
	MessageBox(msg, title);
}

void CCapturePreviewDlg::RefreshVideoModeList()
{
	vector<CString>	modeNames;
	unsigned int	modeIndex = 0;

	// Clear the menu
	m_modeListCombo.ResetContent();

	// Get the mode names
	m_selectedDevice->GetDisplayModeNames(modeNames);

	// Add them to the menu
	while (modeIndex < modeNames.size())
		m_modeListCombo.AddString(modeNames[modeIndex++]);

	m_modeListCombo.SetCurSel(0);
}

void CCapturePreviewDlg::StartCapture()
{
	bool applyDetectedInputMode = (m_applyDetectedInputModeCheckbox.GetCheck() == BST_CHECKED);

	if (m_selectedDevice &&
		m_selectedDevice->StartCapture(m_modeListCombo.GetCurSel(), m_previewWindow, applyDetectedInputMode))
	{
		// Update UI
		m_startStopButton.SetWindowText(_T("Stop capture"));
		EnableInterface(false);
	}
}
void CCapturePreviewDlg::StartCapture(DeckLinkDevice*  m_selectedDevice, PreviewWindow*			m_previewWindow)
{
	bool applyDetectedInputMode = (m_applyDetectedInputModeCheckbox.GetCheck() == BST_CHECKED);

	if (m_selectedDevice &&
		m_selectedDevice->StartCapture(m_modeListCombo.GetCurSel(), m_previewWindow, applyDetectedInputMode))
	{
		// Update UI
		m_startStopButton.SetWindowText(_T("Stop capture"));
		EnableInterface(false);
	}
}



void CCapturePreviewDlg::StopCapture()
{
	if (m_selectedDevice)
		m_selectedDevice->StopCapture();

	// Update UI
	m_startStopButton.SetWindowText(_T("Start capture&stitching"));
	EnableInterface(true);
	m_invalidInputLabel.ShowWindow(SW_HIDE);
}
void CCapturePreviewDlg::StopCapture(DeckLinkDevice*  m_selectedDevice)
{
	if (m_selectedDevice)
		m_selectedDevice->StopCapture();

	// Update UI
	m_startStopButton.SetWindowText(_T("Start capture&stitching"));
	EnableInterface(true);
	m_invalidInputLabel.ShowWindow(SW_HIDE);
}

void CCapturePreviewDlg::EnableInterface(bool enabled)
{
	m_deviceListCombo.EnableWindow((enabled) ? TRUE : FALSE);
	m_modeListCombo.EnableWindow((enabled) ? TRUE : FALSE);

	if (enabled)
	{
		if (m_selectedDevice && m_selectedDevice->SupportsFormatDetection())
		{
			m_applyDetectedInputModeCheckbox.EnableWindow(TRUE);
		}
		else
		{
			m_applyDetectedInputModeCheckbox.EnableWindow(FALSE);
			m_applyDetectedInputModeCheckbox.SetCheck(BST_UNCHECKED);
		}
	}
	else
		m_applyDetectedInputModeCheckbox.EnableWindow(FALSE);
}

BOOL	CCapturePreviewDlg::OnInitDialog()
{
	CDialog::OnInitDialog();
	SetIcon(m_hIcon, FALSE);

	// Empty popup menus
	m_deviceListCombo.ResetContent();
	m_modeListCombo.ResetContent();

	// Disable the interface
	m_startStopButton.EnableWindow(FALSE);
	EnableInterface(false);

	// Create and initialise preview and DeckLink device discovery objects 
	m_previewWindow = new PreviewWindow(this);
	m_previewWindow2 = new PreviewWindow(this);
	m_previewWindow3 = new PreviewWindow(this);
	m_previewWindow4 = new PreviewWindow(this);
	if (m_previewWindow->init(&m_previewBox) == false)
	{
		ShowErrorMessage(_T("This application was unable to initialise the preview window 1"), _T("Error"));
		goto bail;
	}
	if (m_previewWindow2->init(&m_previewBox2) == false)
	{
		ShowErrorMessage(_T("This application was unable to initialise the preview window 2"), _T("Error"));
		goto bail;
	}
	if (m_previewWindow3->init(&m_previewBox3) == false)
	{
		ShowErrorMessage(_T("This application was unable to initialise the preview window 3"), _T("Error"));
		goto bail;
	}
	if (m_previewWindow4->init(&m_previewBox4) == false)
	{
		ShowErrorMessage(_T("This application was unable to initialise the preview window 4"), _T("Error"));
		goto bail;
	}

	m_deckLinkDiscovery = new DeckLinkDeviceDiscovery(this);
	if (!m_deckLinkDiscovery->Enable())
		ShowErrorMessage(_T("Please install the Blackmagic Desktop Video drivers to use the features of this application."), _T("This application requires the Desktop Video drivers installed."));
	//if (m_previewWindow->initStitching() == false)
	//{
	//	ShowErrorMessage(_T("This application was unable to initialise stitching concept "), _T("Error"));
	//	goto bail;
	//}
bail:
	return TRUE;
}
 
void CCapturePreviewDlg::AddDevice(IDeckLink* deckLink)
{
	m_pDeckLink = deckLink;
	int deviceIndex;
	DeckLinkDevice* newDevice = new DeckLinkDevice(this, deckLink);

	// Initialise new DeckLinkDevice object
	if (!newDevice->Init())
	{
		newDevice->Release();
		return;
	}

	// Add this DeckLink device to the device list
	CString  str, str2;
	char s[12];
	itoa(device_count, s, 10);
	str = s;
	CString temp(_T(' '), 2);

	str2 = newDevice->GetDeviceName();
	str2 += temp;
	str2 += str;
	deviceIndex = m_deviceListCombo.AddString(str2);
	if (deviceIndex < 0)
		return;

	m_deviceListCombo.SetItemDataPtr(deviceIndex, newDevice);
	int selectedDeviceIndex = 0;
	if (m_deviceListCombo.GetCount() == 1)
	{
		// We have added our first item, refresh and enable UI
		m_deviceListCombo.SetCurSel(0);
		OnNewDeviceSelected(); //kevin
		{

			m_selectedDevice = (DeckLinkDevice*)m_deviceListCombo.GetItemDataPtr(selectedDeviceIndex);

			// Update the video mode popup menu
			RefreshVideoModeList();

			// Enable the interface
			EnableInterface(true);

			if (m_selectedDevice->SupportsFormatDetection())
				m_applyDetectedInputModeCheckbox.SetCheck(BST_CHECKED);

		}
		m_startStopButton.EnableWindow(TRUE);
		EnableInterface(true);
		 
	}
	//OnNewDeviceSelected(); //kevin replace
	else if (m_deviceListCombo.GetCount() == 2)
	{
		// We have added our first item, refresh and enable UI
		m_deviceListCombo.SetCurSel(0);
		OnNewDeviceSelected(); //kevin
		{
			selectedDeviceIndex = 1;
			m_selectedDevice2 = (DeckLinkDevice*)m_deviceListCombo.GetItemDataPtr(selectedDeviceIndex);

			// Update the video mode popup menu
			RefreshVideoModeList();

			// Enable the interface
			EnableInterface(true);

			if (m_selectedDevice->SupportsFormatDetection())
				m_applyDetectedInputModeCheckbox.SetCheck(BST_CHECKED);

		}
		m_startStopButton2.EnableWindow(TRUE);
		EnableInterface(true);
		 
	}
	else if (m_deviceListCombo.GetCount() == 3)
	{
		// We have added our first item, refresh and enable UI
		m_deviceListCombo.SetCurSel(0);
		OnNewDeviceSelected(); //kevin
		{
			selectedDeviceIndex = 2;
			m_selectedDevice3 = (DeckLinkDevice*)m_deviceListCombo.GetItemDataPtr(selectedDeviceIndex);

			// Update the video mode popup menu
			RefreshVideoModeList();

			// Enable the interface
			EnableInterface(true);

			if (m_selectedDevice3->SupportsFormatDetection())
				m_applyDetectedInputModeCheckbox.SetCheck(BST_CHECKED);

		}
		m_startStopButton3.EnableWindow(TRUE);
		EnableInterface(true);
		 
	}
	else if (m_deviceListCombo.GetCount() == 4)
	{
		// We have added our first item, refresh and enable UI
		m_deviceListCombo.SetCurSel(0);
		OnNewDeviceSelected(); //kevin
		{
			selectedDeviceIndex = 3;
			m_selectedDevice4 = (DeckLinkDevice*)m_deviceListCombo.GetItemDataPtr(selectedDeviceIndex);

			// Update the video mode popup menu
			RefreshVideoModeList();

			// Enable the interface
			EnableInterface(true);

			if (m_selectedDevice4->SupportsFormatDetection())
				m_applyDetectedInputModeCheckbox.SetCheck(BST_CHECKED);

		}
		m_startStopButton4.EnableWindow(TRUE);
		EnableInterface(true);

	}
}
void CCapturePreviewDlg::RemoveDevice(IDeckLink* deckLink)
{
	int deviceIndex = -1;
	DeckLinkDevice* deviceToRemove = NULL;

	// Find the combo box entry to remove (there may be multiple entries with the same name, but each
	// will have a different data pointer).
	for (deviceIndex = 0; deviceIndex < m_deviceListCombo.GetCount(); ++deviceIndex)
	{
		deviceToRemove = (DeckLinkDevice*)m_deviceListCombo.GetItemDataPtr(deviceIndex);
		if (deviceToRemove->DeckLinkInstance() == deckLink)
			break;
	}

	if (deviceToRemove == NULL)
		return;

	// Stop capturing before removal
	if (deviceToRemove->IsCapturing())
		deviceToRemove->StopCapture();

	// Remove device from list
	m_deviceListCombo.DeleteString(deviceIndex);

	// Refresh UI
	m_startStopButton.SetWindowText(_T("Start capture&stitching"));

	// Check how many devices are left
	if (m_deviceListCombo.GetCount() == 0)
	{
		// We have removed the last device, disable the interface.
		m_startStopButton.EnableWindow(FALSE);
		EnableInterface(false);
		m_selectedDevice = NULL;
	}
	else if (m_selectedDevice == deviceToRemove)
	{
		// The device that was removed was the one selected in the UI.
		// Select the first available device in the list and reset the UI.
		m_deviceListCombo.SetCurSel(0);
		OnNewDeviceSelected();

		m_startStopButton.EnableWindow(TRUE);
		m_invalidInputLabel.ShowWindow(SW_HIDE);
	}

	// Release DeckLinkDevice instance
	deviceToRemove->Release();
}

void	CCapturePreviewDlg::UpdateAncillaryData(AncillaryDataStruct& ancillaryData)
{
	// Copy ancillary data under protection of critsec object
	m_critSec.Lock();
	m_ancillaryData = ancillaryData;
	m_critSec.Unlock();
}

LRESULT  CCapturePreviewDlg::OnRefreshInputStreamData(WPARAM wParam, LPARAM lParam)
{
	// Update the UI under protection of critsec object

	m_critSec.Lock();

	m_vitcTcF1.SetWindowText(m_ancillaryData.vitcF1Timecode);
	m_vitcUbF1.SetWindowText(m_ancillaryData.vitcF1UserBits);
	m_vitcTcF2.SetWindowText(m_ancillaryData.vitcF2Timecode);
	m_vitcUbF2.SetWindowText(m_ancillaryData.vitcF2UserBits);

	m_rp188Vitc1Tc.SetWindowText(m_ancillaryData.rp188vitc1Timecode);
	m_rp188Vitc1Ub.SetWindowText(m_ancillaryData.rp188vitc1UserBits);
	m_rp188Vitc2Tc.SetWindowText(m_ancillaryData.rp188vitc2Timecode);
	m_rp188Vitc2Ub.SetWindowText(m_ancillaryData.rp188vitc2UserBits);
	m_rp188LtcTc.SetWindowText(m_ancillaryData.rp188ltcTimecode);
	m_rp188LtcUb.SetWindowText(m_ancillaryData.rp188ltcUserBits);

	m_critSec.Unlock();

	m_invalidInputLabel.ShowWindow((wParam) ? SW_SHOW : SW_HIDE);

	return 0;
}

LRESULT CCapturePreviewDlg::OnSelectVideoMode(WPARAM wParam, LPARAM lParam)
{
	// A new video mode was selected by the user
	m_modeListCombo.SetCurSel((unsigned int)wParam);
	return 0;
}


LRESULT CCapturePreviewDlg::OnAddDevice(WPARAM wParam, LPARAM lParam)
{
	// A new device has been connected
	AddDevice((IDeckLink*)wParam);
	device_count++;
	return 0;
}

LRESULT	CCapturePreviewDlg::OnRemoveDevice(WPARAM wParam, LPARAM lParam)
{
	// An existing device has been disconnected
	RemoveDevice((IDeckLink*)wParam);
	return 0;
}

LRESULT	CCapturePreviewDlg::OnErrorRestartingCapture(WPARAM wParam, LPARAM lParam)
{
	// A change in the input video mode was detected, but the capture could not be restarted.
	StopCapture();
	ShowErrorMessage(_T("This application was unable to apply the detected input video mode."), _T("Error restarting the capture."));
	return 0;
}

void CCapturePreviewDlg::OnPaint()
{
	if (IsIconic())
	{
		CPaintDC dc(this); // device context for painting

		SendMessage(WM_ICONERASEBKGND, reinterpret_cast<WPARAM>(dc.GetSafeHdc()), 0);

		// Center icon in client rectangle
		int cxIcon = GetSystemMetrics(SM_CXICON);
		int cyIcon = GetSystemMetrics(SM_CYICON);
		CRect rect;
		GetClientRect(&rect);
		int x = (rect.Width() - cxIcon + 1) / 2;
		int y = (rect.Height() - cyIcon + 1) / 2;

		// Draw the icon
		dc.DrawIcon(x, y, m_hIcon);
	}
	else
	{
		CDialog::OnPaint();
	}
}

// The system calls this function to obtain the cursor to display while the user drags
//  the minimized window.
HCURSOR CCapturePreviewDlg::OnQueryDragIcon()
{
	return static_cast<HCURSOR>(m_hIcon);
}



void CCapturePreviewDlg::OnBnClickedStartStopButton2()
{
	// TODO: Add your control notification handler code here
	if (m_selectedDevice2 == NULL)
		return;

	if (m_selectedDevice2->IsCapturing())
		StopCapture(m_selectedDevice2);
	else
		StartCapture(m_selectedDevice2, m_previewWindow2);
}


void CCapturePreviewDlg::OnBnClickedStartStopButton3()
{
	// TODO: Add your control notification handler code here
	if (m_selectedDevice3 == NULL)
		return;

	if (m_selectedDevice3->IsCapturing())
		StopCapture(m_selectedDevice3);
	else
		StartCapture(m_selectedDevice3, m_previewWindow3);
}


void CCapturePreviewDlg::OnBnClickedStartStopButton4()
{
	// TODO: Add your control notification handler code here
	if (m_selectedDevice4 == NULL)
		return;

	if (m_selectedDevice4->IsCapturing())
		StopCapture(m_selectedDevice4);
	else
		StartCapture(m_selectedDevice4, m_previewWindow4);
}

